In [ ]:
import pandas as pd # 라이브러리 임포트 (보통 이와 같이 사용함, 이후에는 pd.팬더스함수 형태로 팬더스 라이브러리 함수를 호출함)

In [3]:
import pandas as pd # 라이브러리 임포트 (보통 이와 같이 사용함, 이후에는 pd.팬더스함수 형태로 팬더스 라이브러리 함수를 호출함)
seriesdata = pd.Series([70, 60, 90])
seriesdata

0    70
1    60
2    90
dtype: int64

In [4]:
import pandas as pd # 라이브러리 임포트 (보통 이와 같이 사용함, 이후에는 pd.팬더스함수 형태로 팬더스 라이브러리 함수를 호출함)
seriesdata = pd.Series([70, 60, 90], index=['국어', '영어', '수학'])
seriesdata

국어    70
영어    60
수학    90
dtype: int64

In [5]:
seriesdata.index

Index(['국어', '영어', '수학'], dtype='object')

In [6]:
seriesdata.index = ['미술', '음악', '체육']

In [7]:
seriesdata

미술    70
음악    60
체육    90
dtype: int64

In [8]:
seriesdata.values # seriesdata.values = [] 형태로는 직접 수정이 안됨
print (seriesdata['미술'], seriesdata.iloc[0])

70 70

In [9]:
seriesdata

미술    70
음악    60
체육    90
dtype: int64

In [10]:
del seriesdata['미술']

In [11]:
seriesdata

음악    60
체육    90
dtype: int64

In [12]:
seriesdata = pd.Series(['dave', 'alex', 'amir'])
seriesdata

0    dave
1    alex
2    amir
dtype: object

In [13]:
seriesdata = pd.Series([1, 1, 1])
seriesdata

0    1
1    1
2    1
dtype: int64

In [14]:
seriesdata.astype('float')

0    1.0
1    1.0
2    1.0
dtype: float64

In [15]:
seriesdata = pd.Series(['dave', 1.1, 1.2])
seriesdata

0    dave
1     1.1
2     1.2
dtype: object

In [16]:
seriesdata = pd.Series([True, True, False])
seriesdata

0     True
1     True
2    False
dtype: bool

In [17]:
df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]    
})
df

    미국    한국  중국
0  2.1  0.40  10
1  2.2  0.50  13
2  2.3  0.45  15

In [18]:
df = pd.DataFrame({
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]},
    index=[2000, 2010, 2020]
)
df

       미국    한국  중국
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [19]:
# 행(row) 방향 index
df.index

Index([2000, 2010, 2020], dtype='int64')

In [20]:
df.index = [2001, 2002, 2003]
df

       미국    한국  중국
2001  2.1  0.40  10
2002  2.2  0.50  13
2003  2.3  0.45  15

In [21]:
# 열(column) 방향 index
df.columns

Index(['미국', '한국', '중국'], dtype='object')

In [22]:
df.columns = ['일본', '필리핀', '러시아']
df.values

array([[ 2.1 ,  0.4 , 10.  ],
       [ 2.2 ,  0.5 , 13.  ],
       [ 2.3 ,  0.45, 15.  ]])

In [23]:
df = pd.DataFrame({
    "년도": [2000, 2010, 2020],    
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]    
})
df

     년도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [24]:
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [25]:
df.index.name

'년도'

In [26]:
df.index.name = '연도'
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [27]:
df = df.reset_index('연도')
df

     연도   미국    한국  중국
0  2000  2.1  0.40  10
1  2010  2.2  0.50  13
2  2020  2.3  0.45  15

In [28]:
df = df.set_index('연도')
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [29]:
df.loc[2000]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [30]:
df.iloc[0]

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [31]:
type(df['미국'])

pandas.core.series.Series

In [33]:
df['미국']
df

       미국    한국  중국
연도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [35]:
print (df['한국'][2000])
print (df.loc[2000]['중국'])

0.4
10.0

In [36]:
import pandas as pd

df = pd.DataFrame({
    "년도": ['2000', '2010', '2020'],    
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]    
})
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [37]:
df.index

Index(['2000', '2010', '2020'], dtype='object', name='년도')

In [38]:
df.loc['2000']

미국     2.1
한국     0.4
중국    10.0
Name: 2000, dtype: float64

In [39]:
df['일본'] = [1, 2, 3]
df

       미국    한국  중국  일본
년도
2000  2.1  0.40  10   1
2010  2.2  0.50  13   2
2020  2.3  0.45  15   3

In [40]:
del df['일본']
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [41]:
df = pd.DataFrame({
    "년도": ['2000', '2010', '2020'],    
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]    
})
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [42]:
df.drop(['2020'])

       미국   한국  중국
년도
2000  2.1  0.4  10
2010  2.2  0.5  13

In [43]:
df = pd.DataFrame({
    "년도": ['2000', '2010', '2020'],    
    "미국": [2.1, 2.2, 2.3],
    "한국": [0.4, 0.5, 0.45],
    "중국": [10, 13, 15]    
})
df = df.set_index('년도')
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15

In [44]:
df2 = df[['중국', '한국']].copy()
df2

      중국    한국
년도
2000  10  0.40
2010  13  0.50
2020  15  0.45

In [45]:
df2 = df[['중국', '한국']].copy()
df2

      중국    한국
년도
2000  10  0.40
2010  13  0.50
2020  15  0.45

In [46]:
df2.columns = ['브라질', '아르헨티나']
df2

      브라질  아르헨티나
년도
2000   10   0.40
2010   13   0.50
2020   15   0.45

In [47]:
df

       미국    한국  중국
년도
2000  2.1  0.40  10
2010  2.2  0.50  13
2020  2.3  0.45  15